path: /Users/mac/Coding/inżynieria uczenia maszynowego/training_images/all/new
train: images/train 
val: images/val  

names: 
  0: car
  1: forest
  2: road
  3: building
  4: water
  5: grass
  6: person